#logging:
#    level:
#        root: WARN
#        org.springframework.web: DEBUG
#        org.springframework.security: DEBUG
#        org.springframework.security.oauth2: DEBUG

spring:
    profiles:
        active: dev2

---
# 基于内存存储令牌
server:
    port: 8001
spring:
    profiles: dev0
---
# 基于jdbc存储令牌
server:
    port: 8101
spring:
    profiles: dev1
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/client?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: 123456ly
---
# jwt存储令牌
server:
    port: 8201
spring:
    profiles: dev2

---
# jwt存储令牌增强token
server:
    port: 8301
spring:
    profiles: dev3

---