spring:
    datasource:
        username: root
        password: diyu654321
        url: jdbc:mysql://192.168.1.205:3306/subway?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: tian.pusen.entity

#showSql
logging:
    level:
        tian:
            pusen:
                mapper : debug