server:
    port: 8080
spring:
    profiles:
        active: dev2

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        druid:
            # 连接池的配置信息
            # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
            initialSize: 2
            minIdle: 1
            maxIdle: 5
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            #        validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            maxOpenPreparedStatements: 20
            useGlobalDataSourceStat: true
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            web-stat-filter:
                enabled: true
                url-pattern: "/*"
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
                session-stat-max-count: 1000
                session-stat-enable: true
                profile-enable: true
            stat-view-servlet:
                enabled: true
                url-pattern: "/druid/*"
                login-username: admin
                login-password: admin
                allow: 127.0.0.1,192.168.1.204
                reset-enable: true

mybatis-plus:
    # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
    # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
    mapper-locations: classpath:mapper/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: tian.pusen.data.entity

    configuration:
        #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
        map-underscore-to-camel-case: true
        cache-enabled: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: true
---
spring:
    profiles: dev
    datasource:
        druid:
            url: jdbc:mysql://192.168.1.106:3306/data_dictionary?serverTimezone=Asia/Shanghai
            username: root
            password: ldap4$
            driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
    profiles: dev2
    datasource:
        druid:
            url: jdbc:mysql://192.168.122.249:3306/data-dictionary?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
            username: root
            password: mysql123
            driver-class-name: com.mysql.cj.jdbc.Driver
            # schema: classpath:init/