server:
    port: 9002
security:
    oauth2:
        client:
            client-id: client
            client-secret: secret
            access-token-uri: http://localhost:9000/auth/oauth/token
            user-authorization-uri: http://localhost:9000/auth/oauth/authorize
        resource:
            token-info-uri: http://localhost:9000/auth/oauth/check_token
debug: true