spring:
    datasource:
        username: root
        password: ldap4$
        url: jdbc:mysql://192.168.1.106:3306/data_dictionary
        driver-class-name: com.mysql.jdbc.Driver

#showSql
logging:
    level:
        tian:
            pusen:
                mapper : debug