spring:
    datasource:
        url: jdbc:mysql://192.168.1.205:3306/subway?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: diyu654321
        driver-class-name: com.mysql.jdbc.Driver

#        schema:
#            - "classpath:schema/create.sql"
#            - "classpath:schema/data.sql"
debug: true
logging:
    level:
        org.springframework.jdbc.core.JdbcTemplate: DEBUG