spring:
    profiles:
        active: dev

# 解决数据库建表字段和java字段驼峰写法的一直性映射
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: tian.pusen.entity

#showSql
logging:
    level:
        tian:
            pusen:
                mapper : debug
---
spring:
    profiles: dev
    datasource:
        username: root
        password: mysql123
        url: jdbc:mysql://192.168.122.249:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.jdbc.Driver
---