debug: true
spring:
    thymeleaf:
        cache: false
    messages:
        basename: i18n.message
#server:
#    servlet:
#        context-path: /crud
#    mvc:
#        static-path-pattern=/static/**: