server:
    port: 8080
spring:
    profiles:
        active: dev2

mybatis-plus:
    # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
    # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
    mapper-locations: classpath:mapper/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: tian.pusen.data.entity
#    global-config:
#        dbType: mysql
#        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#        id-type: 3
#        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#        field-strategy: 2
##        #驼峰下划线转换
##        db-column-underline: true
#        #mp2.3+ 全局表前缀 mp_
#        #table-prefix: mp_
#        #刷新mapper 调试神器
#        #refresh-mapper: true
#        #数据库大写下划线转换
#        #capital-mode: true
##        # Sequence序列接口实现类配置
##        key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
##        #逻辑删除配置（下面3个配置）
##        logic-delete-value: 1
##        logic-not-delete-value: 0
##        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
##        #自定义填充策略接口实现
##        meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    configuration:
        #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
        map-underscore-to-camel-case: true
        cache-enabled: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#        #配置JdbcTypeForNull, oracle数据库必须配置
#        jdbc-type-for-null: 'null'

---
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://192.168.1.106:3306/data_dictionary?serverTimezone=Asia/Shanghai
        username: root
        password: ldap4$
        driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
    profiles: dev2
    datasource:
        url: jdbc:mysql://192.168.122.249:3306/data-dictionary?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: mysql123
        driver-class-name: com.mysql.cj.jdbc.Driver
        schema: classpath:init/